// Generado por arte/arte.py: no editar a mano.
package com.jacck.mono.board

import com.jacck.mono.R

/** Arte de cada lugar por su clave (`artKey` del nombre), FA (D-28). */
internal val ArteLugares: Map<String, Int> = mapOf(
    "barichara" to R.drawable.arte_barichara,
    "barranquilla" to R.drawable.arte_barranquilla,
    "bogota" to R.drawable.arte_bogota,
    "buga" to R.drawable.arte_buga,
    "cali" to R.drawable.arte_cali,
    "calle_del_embudo" to R.drawable.arte_calle_del_embudo,
    "cartagena" to R.drawable.arte_cartagena,
    "chapinero" to R.drawable.arte_chapinero,
    "cienaga" to R.drawable.arte_cienaga,
    "estacion_santa_fe" to R.drawable.arte_estacion_santa_fe,
    "filandia" to R.drawable.arte_filandia,
    "guane" to R.drawable.arte_guane,
    "guatape" to R.drawable.arte_guatape,
    "hamaca" to R.drawable.arte_hamaca,
    "jardin" to R.drawable.arte_jardin,
    "jerico" to R.drawable.arte_jerico,
    "la_perseverancia" to R.drawable.arte_la_perseverancia,
    "las_cruces" to R.drawable.arte_las_cruces,
    "leticia" to R.drawable.arte_leticia,
    "loteria" to R.drawable.arte_loteria,
    "manizales" to R.drawable.arte_manizales,
    "marsella" to R.drawable.arte_marsella,
    "medellin" to R.drawable.arte_medellin,
    "mirador" to R.drawable.arte_mirador,
    "mompox" to R.drawable.arte_mompox,
    "mongua" to R.drawable.arte_mongua,
    "palmira" to R.drawable.arte_palmira,
    "puerto_gaitan" to R.drawable.arte_puerto_gaitan,
    "raquira" to R.drawable.arte_raquira,
    "rionegro" to R.drawable.arte_rionegro,
    "salento" to R.drawable.arte_salento,
    "san_andres" to R.drawable.arte_san_andres,
    "san_gil" to R.drawable.arte_san_gil,
    "san_victorino" to R.drawable.arte_san_victorino,
    "santa_marta" to R.drawable.arte_santa_marta,
    "sorpresa" to R.drawable.arte_sorpresa,
    "tierra_de_la_aventura" to R.drawable.arte_tierra_de_la_aventura,
    "tierra_de_la_frontera" to R.drawable.arte_tierra_de_la_frontera,
    "tierra_del_futuro" to R.drawable.arte_tierra_del_futuro,
    "topaga" to R.drawable.arte_topaga,
    "tulua" to R.drawable.arte_tulua,
    "villa_de_leyva" to R.drawable.arte_villa_de_leyva,
    "villavicencio" to R.drawable.arte_villavicencio,
    "yopal" to R.drawable.arte_yopal,
    "zapatoca" to R.drawable.arte_zapatoca,
)
