// Generado por arte/arte.py: no editar a mano.
package com.jacck.mono.board

import com.jacck.mono.R

/** Arte de cada lugar por su clave (`artKey` del nombre), FA (D-28). */
internal val ArteLugares: Map<String, Int> = mapOf(
    "avenida_jimenez" to R.drawable.arte_avenida_jimenez,
    "barichara" to R.drawable.arte_barichara,
    "barranquilla" to R.drawable.arte_barranquilla,
    "barrio_egipto" to R.drawable.arte_barrio_egipto,
    "bogota" to R.drawable.arte_bogota,
    "buga" to R.drawable.arte_buga,
    "cali" to R.drawable.arte_cali,
    "calle_19" to R.drawable.arte_calle_19,
    "calle_del_embudo" to R.drawable.arte_calle_del_embudo,
    "carrera_septima" to R.drawable.arte_carrera_septima,
    "cartagena" to R.drawable.arte_cartagena,
    "cedritos" to R.drawable.arte_cedritos,
    "chapinero" to R.drawable.arte_chapinero,
    "cienaga" to R.drawable.arte_cienaga,
    "el_chico" to R.drawable.arte_el_chico,
    "estacion_de_la_sabana" to R.drawable.arte_estacion_de_la_sabana,
    "estacion_del_norte" to R.drawable.arte_estacion_del_norte,
    "estacion_del_oriente" to R.drawable.arte_estacion_del_oriente,
    "estacion_del_sur" to R.drawable.arte_estacion_del_sur,
    "estacion_santa_fe" to R.drawable.arte_estacion_santa_fe,
    "filandia" to R.drawable.arte_filandia,
    "galerias" to R.drawable.arte_galerias,
    "guane" to R.drawable.arte_guane,
    "guatape" to R.drawable.arte_guatape,
    "hamaca" to R.drawable.arte_hamaca,
    "jardin" to R.drawable.arte_jardin,
    "jerico" to R.drawable.arte_jerico,
    "la_perseverancia" to R.drawable.arte_la_perseverancia,
    "la_soledad" to R.drawable.arte_la_soledad,
    "las_cruces" to R.drawable.arte_las_cruces,
    "leticia" to R.drawable.arte_leticia,
    "loteria" to R.drawable.arte_loteria,
    "manizales" to R.drawable.arte_manizales,
    "marsella" to R.drawable.arte_marsella,
    "medellin" to R.drawable.arte_medellin,
    "mirador" to R.drawable.arte_mirador,
    "mompox" to R.drawable.arte_mompox,
    "mongua" to R.drawable.arte_mongua,
    "niza" to R.drawable.arte_niza,
    "palermo" to R.drawable.arte_palermo,
    "palmira" to R.drawable.arte_palmira,
    "park_way" to R.drawable.arte_park_way,
    "pasadena" to R.drawable.arte_pasadena,
    "puerto_gaitan" to R.drawable.arte_puerto_gaitan,
    "raquira" to R.drawable.arte_raquira,
    "rionegro" to R.drawable.arte_rionegro,
    "rosales" to R.drawable.arte_rosales,
    "salento" to R.drawable.arte_salento,
    "san_andres" to R.drawable.arte_san_andres,
    "san_gil" to R.drawable.arte_san_gil,
    "san_victorino" to R.drawable.arte_san_victorino,
    "santa_barbara" to R.drawable.arte_santa_barbara,
    "santa_marta" to R.drawable.arte_santa_marta,
    "sorpresa" to R.drawable.arte_sorpresa,
    "teusaquillo" to R.drawable.arte_teusaquillo,
    "tierra_de_la_aventura" to R.drawable.arte_tierra_de_la_aventura,
    "tierra_de_la_frontera" to R.drawable.arte_tierra_de_la_frontera,
    "tierra_del_futuro" to R.drawable.arte_tierra_del_futuro,
    "topaga" to R.drawable.arte_topaga,
    "tulua" to R.drawable.arte_tulua,
    "usaquen" to R.drawable.arte_usaquen,
    "villa_de_leyva" to R.drawable.arte_villa_de_leyva,
    "villavicencio" to R.drawable.arte_villavicencio,
    "yopal" to R.drawable.arte_yopal,
    "zapatoca" to R.drawable.arte_zapatoca,
    "zona_t" to R.drawable.arte_zona_t,
)
